environment:
  TEST_CONNECTION_STRING: Server=(local)\SQL2017;Database=MyDatabase_test;User ID=sa;Password=Password12!

services:
  - mssql2017

after_build:
- del MyDatabase\bin\Debug\master.dacpac

artifacts:
- path: MyDatabase\bin\Debug\MyDatabase.dacpac
  name: test
  
deploy:
- provider: SqlDatabase
  artifact: test
  connection_string: $(TEST_CONNECTION_STRING)

# make sure tables have been created
on_success:
  - ps: |
        $conn = New-Object System.Data.SqlClient.SqlConnection
        $conn.ConnectionString = $env:TEST_CONNECTION_STRING
        $conn.Open()
        $cmd = New-Object System.Data.SqlClient.SqlCommand("SELECT * FROM information_schema.tables", $conn)
        $reader = $cmd.ExecuteReader()
        while($reader.Read())
        {
          Write-Host "Table: $($reader["table_name"])"
        }
        $conn.Close()
